trigger:
- main

pool:
  name: 'maventest'

steps:
- script: mvn clean test package
  displayName: 'Build, Test and Package'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/surefire-reports/TEST-*.xml'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'target'
    artifactName: 'drop'